name: Documentation
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Generate Documentation
        run: ./gradlew dokkaHtml
